# alembic/script.py.mako
"""Add VBank integration fields to Account and Transaction models

Revision ID: f05ee718e966
Revises: 090c1a402a7e
Create Date: 2025-11-21 00:28:56.303250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05ee718e966'
down_revision = '090c1a402a7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('provider', sa.String(), nullable=True))
    op.create_index(op.f('ix_accounts_external_id'), 'accounts', ['external_id'], unique=False)
    op.add_column('transactions', sa.Column('category_guess', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'provider')
    op.drop_column('transactions', 'category_guess')
    op.drop_index(op.f('ix_accounts_external_id'), table_name='accounts')
    op.drop_column('accounts', 'provider')
    op.drop_column('accounts', 'external_id')
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###